apiVersion: 1

datasources:
  - name: Netmon InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: netmon
    user:
    password:
    jsonData:
      httpMode: GET
      # For InfluxQL (Influx 1.x)
      httpHeaderName1: ''
    isDefault: true
    editable: false
